#!/usr/bin/env bash

shopt -s globstar

# check pre-reqs
apps=(esbuild minify zola)

for app in "${apps[@]}"; do
  if ! command -v $app > /dev/null; then
    echo "error: need install $app" >&2
    exit 1
  fi
done

# get push msg
while true; do
  read -p 'Push msg: ' msg
  [[ "$msg"  ]] && break
done

# zola build
zola build

# minify
public="$(pwd)/public"

for file in "$public"/**/*.{css,html,js}; do
  [[ -f "$file"  ]] && minify "$file" -o "$file"
done

# bundle css
# cat theme.css base.css layout.css nav.css section.css animation.css >"$public"/style.css

# bundle js
# esbuild "$public/js/script.js" \
#   --bundle \
#   --minify \
#   --allow-overwrite \
#   --outfile="$public/js/script.js"

# push files
git add -A
git commit -m "${msg^}"
git push

exit 0
