baseURL: /
title: Vitor Melo
theme: vitormelo
tag: [vitormelo, vitor melo, piabetá, magé, rj, brasil, design, designer, interface, ux, mobile, responsive, html, markdown, css, sass, js, javascrip, jquery, photoshop]
DefaultContentLanguage: pt-br
