#!/usr/bin/env bash

# Check arguments
[[ $1 ]] || { echo error: need a comment; exit 1; }
msg="$*"

# Check dependencies
deps=(minify zola)

for dep in ${deps[@]}; do
  if ! type $dep &> /dev/null; then
    echo "error: '$dep' not exist"; exit 1
  fi
done

# Build
zola build

# Minify
echo Minifiy files...

public="$(pwd)/public"
cssdir="$public/css"
jsdir="$public/js"

if [[ ! -d "$cssdir" ]]; then
  echo "error: '$cssdir' not exist"; exit 1
fi

if [[ ! -d "$jsdir" ]]; then
  echo "error: '$jsdir' not exist"; exit 1
fi

for file in "$public"/*.{html,xml}; do minify -q "$file" -o "$file"; done
for file in "$jsdir"/*.js; do minify -q "$file" -o "$file"; done
minify -q -b "$cssdir"/{theme,reset,layout,nav,pages,animation}.css -o "$cssdir"/main.css

# Git Push
echo Git push...
git add -A
git commit -m "${msg^}"
git push

