#!/usr/bin/env bash

# Check dependêncies
check_deps() {
  local deps=('html-minifier' 'lightningcss' 'terser')

  for dep in ${deps[@]}; do
    type $dep &> /dev/null || {
      log err "dependencie '$dep' not exist"
      exit 1
    }
  done
}

main() {
  local project_dir=$(pwd)
  local public_dir="$project_dir/public"
  local assets_dir="$public_dir/assets"
  local css_dir="$assets_dir/css"

  check_deps

  echo Minfiy html files...
  html-minifier --collapse-whitespace "$public_dir/index.html" -o "$public_dir/index.html"

  echo Minify css files...
  bunx lightningcss-cli -m "$css_dir/style.css" -o "$css_dir/style.css"

  # echo Unify js files...
  # cd "$jsdir" && cat \
  #   page-control.js \
  #   color-control.js \
  #   menu.js \
  #   main.js > script.js
  #
  # echo Minify js file...
  # terser script.js -o script.js
}

main
