#!/usr/bin/env bash

# $1: md file
# $2: html output
# $3: template optional

type pandoc &>/dev/null || { echo "pandoc not found"; exit 1; }

md2html() {
  [[ $# -ne 2 ]] || { echo "md2html: fail in convert, needs minimum 2 arguments recive $#"; exit 1; }

  [[ "$1" ]] || { echo "md2html: no md file argument"; exit 1; }
  [[ -f "$1" ]] || { echo "md2html: md file '$1' not found"; exit 1; }

  [[ "$2" ]] || { echo "md2html: no output file argument"; exit 1; }
  [[ -d "${2%/*}" ]] || { mkdir -p "$2"; }

  [[ "$3" ]] && {
    [[ -f "$3" ]] || { echo "md2html: template '$3' not exist"; exit 1; }
  }

  pandoc "$1" --template "$2" --wrap=none -o "$3" 
}
